const caseStudy = {
  title: "H2 Economics Case Study: The UK Air Travel Market",
  extracts: [
    { id: 1, title: "Extract 1", content: `Demand for air travel in the UK has grown by 130% over the past 20 years. This is against a background of an increase in GDP of 54% and a significant fall in air fares. Given the forecast real income growth of around 150% in the period to 2050 we project the demand for air travel could grow by over 200% from 230 million passengers per year in 2005 to 695 million passengers in 2050.\nHowever, the increase in demand for air travel will result in higher carbon emissions. There have been talks about measures to tackle this issue. Imposing a tax on the carbon emissions of aircraft and limiting the capacity of UK airports could reduce demand growth to 115% by 2050. In addition there is scope for a significant shift to high-speed rail travel on domestic journeys and short-haul trips to mainland Europe, which could reduce demand for air travel by up to 8% by 2050. This will, however, require significant investment in rail travel. There is also some scope for substitution of videoconferencing for business travel. This could lead to a reduction of up to 30% in business demand for air travel by 2050. Carbon emissions could also be reduced by an improvement in the efficiency of aircraft engines and in air traffic management. In addition alternative fuels will help to cut emissions.` },
    { id: 2, title: "Extract 2", content: `More taxes on air travel are needed in Britain is to meet its climate change obligations according to Government advisers. In a report published today, the Committee on Climate Change (CCC) has called for a drastic action to curb the predicted growth in air travel including higher taxes on air fares. Holidaymakers are already facing sharp increase in Air Passenger Duty which, by the end of next year, will mean a family of four flying to America will pay £240 in tax. ‘Air tickets are going to get a lot more expensive, but people will become a lot richer over the next 40 years. If you’re going to limit the growth in demand, you do need rising prices, ‘said the Committee’s chief executive. ‘It’s not that demand has to fall in order for us to meet the target, demand can increase but only in a limited way.”\nDespite calling for curbs on airport expansion, the Committee stopped short of calling for plans for Heathrow’s third runway to be abandoned.\nThe report was welcomed by environmental groups. One campaigner said, ‘this report is a reality check which should finally put an end to Government plans to allow a huge expansion in air travel. The Committee says that technology can significantly cut the impact that individual flights have on our climate – but if air travel grows to the dangerous level that industry is pushing for, these benefits will be completely outweighed.’\nHowever, the air travel industry insisted that it could meet the carbon reduction targets without restricting demand for flights. ‘We have already seen a 70% improvement in carbon emissions in the last 40 years. We believe limiting emissions is the answer rather than limiting people’s ability to travel. From 2012, carbon emissions from UK flights will be included in a European Union (EU) scheme, whereby any increase in emissions above the 2005 baseline will have to be matched by equivalent reductions elsewhere, paid for by the air travel industry,’ said the executive chairman of the Airport Operators Association.\nThe chief executive of a short-haul airline added: ‘The key to sustainable air travel is technology, not taxation, and the way to make sure it happens is by setting minimum standards for aircraft emissions.’` },
    { id: 3, title: "Extract 3", content: `The ability to travel combined with the fall in air fares has driven the surge in demand for flights, not just to the UK, but throughout Europe. But a recent report by the Civil Aviation Authority, produced in September, confirms that there has been an exceptional surge in migrant travel to and from Europe. It is this, rather than an increase in holiday or business travel, that has led to the increase in demand for flights since 1990. The question is whether this rise will continue and there is evidence that the rise is beginning to level off. If that is the case, one has to question whether there is any real justification in artificially forcing up air fares, which will not only make air travel the preserve of the rich, but also deny airlines, many of which are making losses at the moment, the money they need to invest in cleaner, more environmentally friendly aircraft in the future.` },
    { id: 4, title: "Extract 4", content: `In recent years, an increasingly globalized world economy has led to a rise in labour mobility and migration, particularly within Europe. At the same time, there has been a relaxation of regulatory restrictions on aviation markets and this has encouraged increases in flights.\nThere is a subset of leisure passengers who travel for the purpose of ‘Visiting Friends or Relatives’ (VFR). Between 2000 and 2007, whilst total passengers to and from the UK grew by one-third, those travelling for the purpose of VFR increased by over three-quarters, much more than the growth in business and holiday travel.\nLooking forward, the current worldwide economic downturn is likely to impact upon VFR traffic, both through falls in UK GDP and changes in migration patterns. For these people, travel for VFR purposes is an indication of the desire to build and maintain relationships. The analysis in this study has been carried out using data which cover a period of significant change in terms of the increase in the number of countries belonging to the EU, the migration flows this has enabled and the liberalization of the EU air travel market (giving rise to more affordable air travel). In light of these one-off developments, it may not be realistic to assume continued growth of the same magnitude.` }
  ],
  tableHTML: `<table class="data-table"><thead><tr><th></th><th>Price Elasticities of Demand</th><th>Income Elasticities of Demand</th></tr></thead><tbody><tr><td>Business flights to UK destinations</td><td>n/a</td><td>1.4</td></tr><tr><td>Leisure flights to UK destinations</td><td>-1.0</td><td>1.5</td></tr><tr><td>Business flights to non-UK destinations</td><td>n/a</td><td>0.6</td></tr><tr><td>Leisure flights to non-UK destinations</td><td>-0.2</td><td>0.7</td></tr></tbody></table><p class="table-note">n/a = not available | Source: UK Department for Trade, 2009</p>`,
  questions: [
    {
      id: "a_i", marks: 2,
      text: "(a)(i) With reference to the data in Table 1, explain the effect on the total revenue from leisure flights to UK destinations of a fall in price.",
      rubric: [
        { mark: 1, concept: "Unitary PED", keywords: ["ped", "-1", "-1.0", "unitary", "proportionate"], positive: "✅ You correctly identified the PED value and its elasticity type.", missing: "🔍 The mark scheme requires you to explicitly state that PED = -1.0 indicates unitary price elasticity.", socratic: "What does the value '-1.0' in Table 1 tell you about how responsive quantity demanded is to price?" },
        { mark: 1, concept: "TR unchanged", keywords: ["total revenue", "unchanged", "offset", "p x q", "price times quantity", "remains the same"], positive: "✅ You correctly linked the elasticity to the impact on total revenue.", missing: "🔍 You need to explain how the fall in price interacts with the change in quantity to affect total revenue.", socratic: "If price falls and quantity rises by the exact same percentage, what happens when you multiply them together?" }
      ],
      pitfalls: [{ trigger: ["revenue", "increase", "rise", "go up", "increases"], feedback: "⚠️ Careful: With unitary elasticity, total revenue does not increase when price falls. The P↓ is exactly offset by Q↑." }]
    },
    {
      id: "a_ii", marks: 2,
      text: "(a)(ii) With reference to the data in Table 1, explain the effect on the total revenue from leisure flights to UK destinations of a fall in income.",
      rubric: [
        { mark: 1, concept: "YED = 1.5 → Luxury", keywords: ["yed", "1.5", "luxury", "normal good", "more than proportionate"], positive: "✅ You correctly identified the income elasticity and good type.", missing: "🔍 State clearly that YED = 1.5 indicates a luxury good (YED > 1).", socratic: "Is YED = 1.5 greater or less than 1? What type of good does this imply for leisure flights?" },
        { mark: 1, concept: "TR falls significantly", keywords: ["total revenue", "falls", "decrease", "drops", "large fall", "ceteris paribus"], positive: "✅ You correctly explained the directional impact on total revenue.", missing: "🔍 Explain how a fall in income causes a more than proportionate drop in demand, leading to a significant fall in TR.", socratic: "When demand for a luxury good falls sharply, what happens to both equilibrium price and quantity? How does that affect P × Q?" }
      ],
      pitfalls: [{ trigger: ["revenue", "rises", "increases", "go up"], feedback: "⚠️ Incorrect: A fall in income reduces demand for a luxury good. Both price and quantity fall, so TR must decrease." }]
    },
    {
      id: "b_i", marks: 2,
      text: "(b)(i) Explain one possible reason why the demand for leisure flights to non-UK destinations is less price-elastic than that for UK destinations.",
      rubric: [
        { mark: 1, concept: "Fewer substitutes internationally", keywords: ["substitutes", "close substitutes", "ferries", "trains", "cars", "longer time", "alternative transport", "international"], positive: "✅ You correctly noted the availability of substitutes differs by route type.", missing: "🔍 Explain that non-UK destinations have fewer close substitutes (e.g., trains/boats take too long).", socratic: "Think about the determinants of PED. How does the availability of substitutes differ between flying overseas vs flying domestically?" },
        { mark: 1, concept: "Contrast with UK domestic", keywords: ["domestic", "uk", "trains", "cars", "close substitutes", "comparison"], positive: "✅ You effectively contrasted international vs domestic travel options.", missing: "🔍 Explicitly contrast with UK domestic travel, where rail and road are close substitutes, making demand more elastic.", socratic: "Why might trains/cars be poor substitutes for long-haul trips but good ones for short-haul?" }
      ],
      pitfalls: [{ trigger: ["price", "expensive", "cost"], feedback: "⚠️ Focus on elasticity determinants (substitutes), not just absolute price levels." }]
    },
    {
      id: "b_ii", marks: 2,
      text: "(b)(ii) Explain one possible reason why the income elasticity of demand for business flights to UK destinations is higher than that for non-UK destinations.",
      rubric: [
        { mark: 1, concept: "Necessity vs discretion", keywords: ["necessity", "discretionary", "less necessary", "local", "easier communication"], positive: "✅ You correctly linked YED differences to the degree of necessity.", missing: "🔍 Higher YED means lower necessity. Explain why UK business travel is more discretionary.", socratic: "Higher YED usually means a good is less of a necessity. Why might a business *need* to fly overseas more than domestically?" },
        { mark: 1, concept: "Physical presence/market info", keywords: ["foreign", "international", "market", "physical presence", "information", "familiarise", "communication"], positive: "✅ You correctly explained the role of market familiarity in business travel decisions.", missing: "🔍 Explain that non-UK business travel requires physical presence to gather foreign market information, making it more necessary (lower YED).", socratic: "How does familiarity with local markets affect the necessity of physical travel?" }
      ],
      pitfalls: [{ trigger: ["income", "rich", "poor"], feedback: "⚠️ YED measures responsiveness to income changes, not who can afford it. Focus on necessity vs discretion." }]
    },
    {
      id: "c", marks: 2,
      text: "(c) Explain the likely value of the cross-elasticity of demand between high-speed rail travel and air travel.",
      rubric: [
        { mark: 1, concept: "CED definition + sign", keywords: ["ced", "cross elasticity", "responsiveness", "price of good b", "demand for good a", "positive", "substitutes"], positive: "✅ You correctly defined CED and identified the relationship type.", missing: "🔍 Define CED and state that rail and air are substitutes, so CED is positive.", socratic: "How do you define cross-elasticity in economic terms? Are rail and air substitutes or complements?" },
        { mark: 1, concept: "Small magnitude (<1)", keywords: ["small", "less than 1", "<1", "short-haul", "domestic", "not close", "limited substitution"], positive: "✅ You correctly explained why the elasticity value is likely small.", missing: "🔍 Explain that CED is small (<1) because rail only substitutes air on short-haul/domestic routes, not long-haul.", socratic: "Can rail replace air for *all* journeys? How does this limitation affect the magnitude of the elasticity?" }
      ],
      pitfalls: [{ trigger: ["negative", "complements", "inversely"], feedback: "⚠️ Rail and air compete for passengers on the same routes. They are substitutes, not complements." }]
    },
    {
      id: "d", marks: 2,
      text: "(d) Explain either one demand or one supply factor that has led to a rise in VFR travel.",
      rubric: [
        { mark: 1, concept: "Identify factor + extract ref", keywords: ["demand", "supply", "migration", "labour mobility", "deregulation", "liberalisation", "restrictions", "extract"], positive: "✅ You correctly identified a relevant factor from the extracts.", missing: "🔍 Explicitly state whether you're analyzing a demand or supply factor, and reference the relevant extract phrase.", socratic: "Pick ONE factor. What specific phrase in Extract 4 points to it?" },
        { mark: 1, concept: "Full economic chain", keywords: ["shortage", "surplus", "price", "quantity", "dd↑", "ss↑", "shift", "equilibrium", "rise in vfr"], positive: "✅ You provided a clear chain of economic reasoning.", missing: "🔍 Show the full mechanism: Factor → Curve shift → Shortage/Surplus → Price change → Quantity change.", socratic: "How does this factor shift the demand or supply curve? What market mechanism follows, and how does it ultimately increase VFR travel?" }
      ],
      pitfalls: [{ trigger: ["just because", "people want to", "more flights"], feedback: "⚠️ H2 examiners require precise economic terminology. Use 'willingness/ability to pay' or 'producer constraints' instead of casual phrasing." }]
    }
  ]
};
